language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true react-app-test npm run test -- --coverage